# -*- coding: utf-8 -*-
"""08_pricing_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHYjwTMy_VsmXbzevozo877CZzK6vfLe
"""

# -*- coding: utf-8 -*-

"""# CatPriceAI — AI Pricing Agent (LangChain Tools + ReAct)

**Student 8 — Agentic AI Engineer**  
Project: CatPriceAI — Property Cat XL Treaty Pricing Workbench  
Module: `08_pricing_agent.py`

---

### 📂 Google Drive Structure Expected
```
Shared with me / RI Project SSSIA /
├── cat_price_ai/                     ← pricing CSVs live here
│   ├── exposure_summary.csv
│   ├── burning_cost.csv
│   ├── pricing_output.csv
│   ├── ml_pricing.csv
│   └── market_rol.csv
├── Output/                   ← RAG artifacts from Student 7
│   ├── bm25.pkl
│   └── vectorstore/
├── cat_price_ai/
├── Goals/
└── ml
```

### Agent Tools
| # | Tool | Source |
|---|------|--------|
| 1 | `GetExposureSummary` | `data/exposure_summary.csv` |
| 2 | `RunBurningCost` | `data/burning_cost.csv` |
| 3 | `GetTechnicalPrice` | `data/pricing_output.csv` + `data/ml_pricing.csv` |
| 4 | `GetMarketBenchmarks` | `data/market_rol.csv` |
| 5 | `QueryTreatyTerms` | RAG: `Output/bm25.pkl` + `Output/vectorstore/` (Student 7) |

"""

from google.colab import drive
drive.mount('/content/drive')

"""## 1. Install Dependencies

"""

"""## 1. Install Dependencies"""
!pip install pandas numpy --quiet
!pip install langchain langchain-openai langchainhub --quiet
!pip install groq --quiet
!pip install langchain-community langchain_huggingface --quiet
!pip install faiss-cpu --quiet
!pip install rank-bm25 --quiet
print('✅ All dependencies installed.')

"""## 2. Mount Google Drive

"""

"""## 2. Mount Google Drive"""
from google.colab import drive
drive.mount('/content/drive')
print('✅ Drive mounted at /content/drive')

"""## 3. Configure Drive Paths

"""

"""## 3. Configure Drive Paths"""
import os, json, pickle
import pandas as pd
import numpy as np
from pathlib import Path
from typing import Optional

# ── Dynamically locate the shared project folder ─────────────
PROJECT_NAME = 'RI Project SSSIA'

SEARCH_ROOTS = [
    Path('/content/drive/MyDrive'),
    Path('/content/drive/Shareddrives'),
    Path('/content/drive/Shared drives'),
    Path('/content/drive/Shared with me'), # Added this path
    Path('/content/drive'),
]

DRIVE_ROOT = None

# 1. Try each known candidate directly
for root in SEARCH_ROOTS:
    candidate = root / PROJECT_NAME
    if candidate.exists():
        DRIVE_ROOT = candidate
        break

# 2. If not found, do a one-level-deep search under /content/drive
if DRIVE_ROOT is None:
    for p in sorted(Path('/content/drive').rglob(PROJECT_NAME)):
        if p.is_dir():
            DRIVE_ROOT = p
            break

if DRIVE_ROOT is None:
    raise FileNotFoundError(
        f"Could not find '{PROJECT_NAME}' anywhere under /content/drive. "
        "Make sure Drive is mounted and the folder is shared with your account."
    )

print(f'✅ Project root found: {DRIVE_ROOT}')

# ── Sub-folder paths ─────────────────────────────────────────
DATA_DIR         = DRIVE_ROOT / 'cat_price_ai'
RAG_DIR          = DRIVE_ROOT / 'Output' / 'Student_7_RAG'
BM25_PATH        = RAG_DIR / 'bm25.pkl'
VECTORSTORE_PATH = RAG_DIR / 'vectorstore'

# ── Individual CSV paths ─────────────────────────────────────
EXPOSURE_CSV = DATA_DIR / 'exposure_summary.csv'
BURNING_CSV  = DATA_DIR / 'burning_cost.csv'
PRICING_CSV  = DATA_DIR / 'pricing_output.csv'
ML_CSV       = DATA_DIR / 'ml_pricing.csv'
MARKET_CSV   = DATA_DIR / 'market_rol.csv'

# ── Verify all paths ─────────────────────────────────────────
print('\nDrive path checks:')
paths_to_check = {
    'Project root':           DRIVE_ROOT,
    'cat_price_ai/ folder':   DATA_DIR,
    'Output/Student_7_RAG/':  RAG_DIR,
    'exposure_summary.csv':   EXPOSURE_CSV,
    'burning_cost.csv':       BURNING_CSV,
    'pricing_output.csv':     PRICING_CSV,
    'ml_pricing.csv':         ML_CSV,
    'market_rol.csv':         MARKET_CSV,
    'bm25.pkl':               BM25_PATH,
    'vectorstore/':           VECTORSTORE_PATH,
}
all_ok = True
for label, path in paths_to_check.items():
    exists = path.exists()
    icon   = '✅' if exists else '❌ MISSING'
    print(f'  {icon}  {label:<25} {path}')
    if not exists:
        all_ok = False

print('\n🎉 All paths found. Ready to run.' if all_ok else '\n⚠️  Some paths are missing.')

"""## 4. API Keys

"""

"""## 4. API Keys"""
from google.colab import userdata

# ── Groq key (for RAG treaty Q&A) ───────────────────────────
try:
    GROQ_API_KEY = userdata.get('GROQ_API_KEY')
    print('✅ GROQ_API_KEY loaded from Colab secrets.')
except Exception:
    GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
    print('⚠️  GROQ_API_KEY not in secrets — set it in Colab → Secrets or paste below.')

# ── OpenAI key (optional — for full ReAct agent) ─────────────
try:
    OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')
    os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY
    print('✅ OPENAI_API_KEY loaded — ReAct agent enabled.')
except Exception:
    OPENAI_API_KEY = ''
    print('ℹ️  No OPENAI_API_KEY — will use offline keyword router (still fully functional).')

USE_OPENAI = bool(os.getenv('OPENAI_API_KEY'))

"""## 5. RAG Components (from Student 7 — `Output/`)

"""

"""## 5. RAG Components (from Student 7 — `Output/`)"""
from rank_bm25 import BM25Okapi
from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from groq import Groq

# ── BM25 Retriever class (must match Student 7 definition) ───
class BM25Retriever:
    def __init__(self, chunks):
        self.chunks = chunks
        corpus = [chunk['content'].lower().split() for chunk in chunks]
        self.bm25 = BM25Okapi(corpus)

    def search(self, query, k=10):
        query_tokens = query.lower().split()
        scores = self.bm25.get_scores(query_tokens)
        ranked = sorted(
            zip(self.chunks, scores),
            key=lambda x: x[1], reverse=True
        )
        return ranked[:k]


# ── Custom unpickler — same as Student 7 ─────────────────────
class CustomUnpickler(pickle.Unpickler):
    def find_class(self, module, name):
        if module == 'bm25_engine' and name == 'BM25Retriever':
            return BM25Retriever
        return super().find_class(module, name)


# ── Groq LLM wrapper ─────────────────────────────────────────
def generate_answer(prompt: str) -> str:
    client = Groq(api_key=GROQ_API_KEY)
    response = client.chat.completions.create(
        model='llama-3.3-70b-versatile',
        messages=[{'role': 'user', 'content': prompt}],
        temperature=0,
        max_tokens=1000
    )
    return response.choices[0].message.content


# ── Hybrid Retriever (FAISS + BM25 Reciprocal Rank Fusion) ───
class HybridRetriever:
    def __init__(self, faiss_vectorstore, bm25_retriever):
        self.faiss = faiss_vectorstore
        self.bm25  = bm25_retriever

    def search(self, query, faiss_k=20, bm25_k=20, final_k=10):
        combined = {}
        for rank, (doc, score) in enumerate(
            self.faiss.similarity_search_with_score(query, k=faiss_k)
        ):
            key = doc.page_content
            combined.setdefault(key, {'doc': doc, 'score': 0})
            combined[key]['score'] += 1.0 / (rank + 1)

        for rank, (chunk, score) in enumerate(self.bm25.search(query, k=bm25_k)):
            key = chunk['content']
            combined.setdefault(key, {'doc': None, 'score': 0})
            combined[key]['score'] += 1.0 / (rank + 1)

        ranked = sorted(combined.values(), key=lambda x: x['score'], reverse=True)
        return [item['doc'] for item in ranked if item['doc'] is not None][:final_k]


# ── RAG Engine ────────────────────────────────────────────────
class RagEngine:
    def __init__(self, retriever):
        self.retriever = retriever

    def ask(self, question: str) -> str:
        docs = self.retriever.search(query=question, final_k=10)
        context = '\n\n'.join(doc.page_content for doc in docs)
        prompt = f"""
You are a Reinsurance Treaty Analysis Assistant.

Instructions:
1. Answer ONLY from the provided context.
2. Do NOT use outside knowledge.
3. If the answer is not found, say: "I could not find the answer in the provided documents."
4. Mention the relevant Article or Section if available.
5. Be concise and professional.

CONTEXT:
{context}

QUESTION:
{question}

ANSWER:"""
        return generate_answer(prompt)


print('✅ RAG classes defined.')

# ── Load BM25 from Drive ──────────────────────────────────────
print('Loading BM25 from Drive...')
with open(BM25_PATH, 'rb') as f:
    bm25 = CustomUnpickler(f).load()
print(f'  ✅ BM25 loaded — {len(bm25.chunks)} chunks')

# ── Load FAISS vectorstore from Drive ────────────────────────
print('Loading FAISS vectorstore from Drive...')
embeddings   = HuggingFaceEmbeddings(model_name='sentence-transformers/all-MiniLM-L6-v2')
vectorstore  = FAISS.load_local(
    str(VECTORSTORE_PATH),
    embeddings,
    allow_dangerous_deserialization=True
)
print('  ✅ FAISS vectorstore loaded.')

# ── Wire up ───────────────────────────────────────────────────
hybrid_retriever = HybridRetriever(vectorstore, bm25)
rag              = RagEngine(hybrid_retriever)
print('  ✅ RAG engine ready.')

"""## 6. Tool Functions (reading CSVs from Drive)

Load first row of a CSV from Drive. Returns None if file missing.
"""

import os, json, pickle
import pandas as pd
import numpy as np
from pathlib import Path
from typing import Optional

"""## 6. Tool Functions (reading CSVs from Drive)"""
def _load_csv(path: Path) -> Optional[pd.Series]:
    """Load first row of a CSV from Drive. Returns None if file missing."""
    if path.exists():
        return pd.read_csv(path).iloc[0]
    return None

"""Returns cedant portfolio exposure stats from Drive data/exposure_summary.csv.

Returns burning cost ROL from Drive data/burning_cost.csv.
"""

def tool_get_exposure_summary() -> str:
    """Returns cedant portfolio exposure stats from Drive data/exposure_summary.csv."""
    data = _load_csv(EXPOSURE_CSV)
    if data is None:
        return f'❌ Not found: {EXPOSURE_CSV}'
    result = {
        'total_tiv_usd_millions':  round(float(data['total_tiv_usd']) / 1e6, 2),
        'num_locations':           int(data['num_locations']),
        'avg_tiv_per_location_k':  round(float(data['avg_tiv_per_location']) / 1000, 1),
        'coastal_50km_pct':        float(data['coastal_50km_tiv_pct']),
        'flood_high_risk_pct':     float(data['flood_high_risk_tiv_pct']),
        'wood_frame_pct':          float(data['wood_frame_tiv_pct']),
        'avg_wind_vulnerability':  float(data['avg_wind_vuln_index']),
        'dominant_state':          str(data['dominant_state']),
        'dominant_state_pct':      float(data['dominant_state_pct']),
    }
    return json.dumps(result, indent=2)


# ── Tool 2: Burning Cost ──────────────────────────────────────
def tool_run_burning_cost() -> str:
    """Returns burning cost ROL from Drive data/burning_cost.csv."""
    data = _load_csv(BURNING_CSV)
    if data is None:
        return f'❌ Not found: {BURNING_CSV}'
    result = {
        'experience_years':        int(data['experience_years']),
        'aal_in_layer_millions':   float(data['aal_m']),
        'burning_cost_rol_pct':    float(data['burning_cost_rol_pct']),
        'layer_penetration_years': int(data['layer_penetration_years']),
        'empirical_frequency_pct': float(data['empirical_freq_pct']),
    }
    return json.dumps(result, indent=2)

# ── Tool 3: Technical Price ───────────────────────────────────
def tool_get_technical_price() -> str:
    """Returns full actuarial pricing from Drive data/pricing_output.csv + ml_pricing.csv."""
    data = _load_csv(PRICING_CSV)
    if data is None:
        return f'❌ Not found: {PRICING_CSV}'
    ml = _load_csv(ML_CSV)
    result = {
        'burning_cost_rol_pct':     round(float(data['burning_cost_rol']) * 100, 2),
        'freq_severity_rol_pct':    round(float(data['freq_severity_rol']) * 100, 2),
        'exposure_rating_rol_pct':  round(float(data['exposure_rating_rol']) * 100, 2),
        'blended_pure_rol_pct':     round(float(data['blended_pure_rol']) * 100, 2),
        'technical_rol_pct':        round(float(data['technical_rol']) * 100, 2),
        'technical_premium_usd':    round(float(data['technical_premium_usd']), 0),
        'market_benchmark_rol_pct': round(float(data['market_benchmark_rol']) * 100, 2),
        'adequacy_vs_market_pct':   round(float(data['adequacy_vs_market_pct']), 2),
        'recommendation':           str(data['recommendation']),
        'layer':                    '$50M xs $50M',
    }
    if ml is not None:
        result['ml_adjustment_factor'] = round(float(ml['ml_adjustment_factor']), 4)
        result['ml_adjusted_rol_pct']  = round(float(ml['ml_adjusted_rol']) * 100, 2)
    return json.dumps(result, indent=2)


# ── Tool 4: Market Benchmarks ─────────────────────────────────
def tool_get_market_benchmarks() -> str:
    """Returns Gulf Coast market ROL benchmarks from Drive data/market_rol.csv."""
    data = _load_csv(MARKET_CSV)
    if data is None:
        return f'❌ Not found: {MARKET_CSV}'
    mkt    = pd.read_csv(MARKET_CSV)
    recent = mkt[(mkt['year'] >= 2021) & (mkt['region'] == 'Gulf Coast')]
    by_peril = (
        recent.groupby('peril')['market_rol']
              .agg(['mean', 'min', 'max'])
              .reset_index()
              .rename(columns={'mean': 'avg_rol', 'min': 'min_rol', 'max': 'max_rol'})
    )
    by_peril[['avg_rol', 'min_rol', 'max_rol']] = (
        by_peril[['avg_rol', 'min_rol', 'max_rol']] * 100
    ).round(2)
    return by_peril.to_json(orient='records', indent=2)


# ── Tool 5: Query Treaty Terms via RAG ───────────────────────
def tool_query_treaty_terms(question: str) -> str:
    """Offline treaty retrieval.
    Uses Student 7 vectorstore only.
    No API keys required."""
    try:
        docs = hybrid_retriever.search(
            query=question,
            final_k=3
        )

        if not docs:
            return "No relevant treaty wording found."

        answer = []

        for i, doc in enumerate(docs, start=1):
            text = doc.page_content.strip()
            answer.append(f"[Retrieved Section {i}]\n{text}")

        return "\n\n".join(answer)

    except Exception as e:
        return f"Treaty retrieval failed: {e}"

print('✅ All 5 tool functions ready (reading from Drive).')

"""## 7. LangChain Tool Wrappers

"""

"""## 7. LangChain Tool Wrappers"""
def build_langchain_tools():
    from langchain_core.tools import Tool
    return [
        Tool(
            name='GetExposureSummary',
            func=lambda _: tool_get_exposure_summary(),
            description=(
                'Returns cedant portfolio exposure statistics: TIV, location count, '
                'coastal concentration, flood zone exposure, construction mix, wind vulnerability. '
                'Use when the user asks about portfolio risk profile or coastal concentration.'
            )
        ),
        Tool(
            name='RunBurningCost',
            func=lambda _: tool_run_burning_cost(),
            description=(
                'Returns burning cost analysis: AAL in the Cat XL layer, ROL, '
                'layer penetration frequency. Use when asked about historical loss-based pricing.'
            )
        ),
        Tool(
            name='GetTechnicalPrice',
            func=lambda _: tool_get_technical_price(),
            description=(
                'Returns the full technical pricing output: all three methods, blended ROL, '
                'technical premium, market comparison, ML adjustment, and recommendation. '
                'Use when the user asks for the price, ROL, adequacy, or whether to quote.'
            )
        ),
        Tool(
            name='GetMarketBenchmarks',
            func=lambda _: tool_get_market_benchmarks(),
            description=(
                'Returns recent (2021-2023) Gulf Coast property cat market ROL benchmarks by peril. '
                'Use when comparing our technical price to the market.'
            )
        ),
        Tool(
            name='QueryTreatyTerms',
            func=tool_query_treaty_terms,
            description=(
                'Queries reinsurance treaty wording using AI (Hybrid RAG: FAISS + BM25 + Groq LLM). '
                'Use for: coverage, exclusions, definitions, clauses, attachment, '
                'MDR, eligibility, claims process, reinstatements, perils. '
                'Input: your specific question as a string.'
            )
        )
    ]

print('✅ LangChain tool wrappers ready.')

"""## 8. PricingAgent Class

"""

class PricingAgent:
    """ReAct-style agent that reasons across all CatPriceAI modules.
    Uses LangChain ReAct (OpenAI) when OPENAI_API_KEY is set;
    otherwise falls back to a keyword router (offline, still fully functional).
    All data read from Google Drive."""

    def __init__(self):
        self.tools = build_langchain_tools()
        self.agent = self._build_agent()
        mode = 'ReAct (OpenAI)' if self.agent else 'Simple Router (offline)'
        print(f'🤖 PricingAgent ready — {mode} mode.')

    def _build_agent(self):
        if not USE_OPENAI:
            return None
        try:
            from langchain_openai import ChatOpenAI
            from langchain.agents import create_react_agent, AgentExecutor
            from langchain import hub
            llm    = ChatOpenAI(model='gpt-4o-mini', temperature=0)
            prompt = hub.pull('hwchase17/react')
            agent  = create_react_agent(llm=llm, tools=self.tools, prompt=prompt)
            return AgentExecutor(agent=agent, tools=self.tools, verbose=True, max_iterations=6)
        except Exception as e:
            print(f'⚠️ ReAct build failed: {e}. Using keyword router.')
            return None

    def run(self, question: str) -> str:
        if self.agent is not None:
            try:
                result = self.agent.invoke({'input': question})
                return result.get('output', str(result))
            except Exception as e:
                return f'Agent error: {e}'
        return self._simple_router(question)

    def _simple_router(self, question: str) -> str:
        """Keyword-based routing — offline fallback."""

        if any(kw in question for kw in ['exposure', 'portfolio', 'tiv', 'location', 'coast',
                                    'flood zone', 'construction', 'wind', 'concentration']):
            return f'EXPOSURE SUMMARY:\n{tool_get_exposure_summary()}'

        elif any(kw in question for kw in ['burning', 'historical', 'loss history', 'aal',
                                      'experience', 'penetration', 'empirical']):
            return f'BURNING COST:\n{tool_run_burning_cost()}'

        elif any(kw in question for kw in ['market', 'benchmark', 'industry', 'competitive',
                                      'compare', 'peers']):
            return f'MARKET BENCHMARKS:\n{tool_get_market_benchmarks()}'

        elif "should we quote" in question or any(kw in question.lower() for kw in ['quote this treaty', 'should we quote']):
            return f'TREATY QUOTE GUIDANCE:\n{tool_query_treaty_terms("Should we quote this treaty? What are the quoting conditions, eligibility criteria, and any clauses relevant to underwriting or declining this treaty?")}'

        elif any(kw in question for kw in ['price', 'rol', 'premium', 'technical', 'recommend',
                                      'quote', 'adequate', 'adequacy', 'ml', 'model',
                                      'blended', 'freq', 'severity']):
            return f'TECHNICAL PRICE:\n{tool_get_technical_price()}'

        elif any(kw in question for kw in ['treaty', 'clause', 'coverage', 'exclusion',
                                      'attachment', 'reinstate', 'peril', 'definition',
                                      'eligib', 'mdr', 'claim', 'wording', 'excluded']):
            return f'TREATY Q&A:\n{tool_query_treaty_terms(question)}'

        else:
            return (
                "I am a pricing agent for the reinsurance treaty and cannot answer questions "
                "unrelated to treaty pricing. I can help with: exposure summary, burning cost, "
                "technical price / ROL, market benchmarks, treaty terms and clauses, or quoting guidance."
            )

print('✅ PricingAgent class defined.')

"""## 9. Demo — Preset Questions from Spec

"""

import os
from pathlib import Path

# Re-define essential path variables in case of kernel state loss
# These are typically defined in cell 'pWATtO3pKbCq'
PROJECT_NAME = 'RI Project SSSIA'
DRIVE_ROOT = Path('/content/drive/MyDrive') / PROJECT_NAME # Assuming MyDrive is the common location
DATA_DIR = DRIVE_ROOT / 'cat_price_ai'

EXPOSURE_CSV = DATA_DIR / 'exposure_summary.csv'
BURNING_CSV  = DATA_DIR / 'burning_cost.csv'
PRICING_CSV  = DATA_DIR / 'pricing_output.csv'
ML_CSV       = DATA_DIR / 'ml_pricing.csv'
MARKET_CSV   = DATA_DIR / 'market_rol.csv'

USE_OPENAI = True

"""## 9. Demo — Preset Questions from Spec"""
DEMO_PROMPTS = [
    'What is our technical price?',
    'What perils are excluded?',
    'How many reinstatements do we get?',
    'What is the burning cost ROL?'
    'Should we quote this treaty?',
]

agent = PricingAgent()

print('=' * 65)
print('DEMO QUESTIONS')
print('=' * 65)
for prompt in DEMO_PROMPTS:
    print(f'\nQ: {prompt}')
    print('-' * 40)
    print(f'A: {agent.run(prompt)}')
print('\n' + '=' * 65)

"""## 10. 💬 Interactive Agent

Change the question and re-run, or use the loop below.

"""

# ── Full interactive loop ────────────────────────────────────
print('=' * 65)
print('INTERACTIVE PRICING AGENT — type quit to stop')
print('=' * 65)
print('Example questions:')
print('  • What is our technical ROL?')
print('  • What perils are excluded?')
print('  • How many reinstatements do we get?')
print('  • What is the burning cost ROL?')
print('  • Should we quote this treaty?')

print()

while True:
    try:
        user_input = input('You: ').strip()
    except (EOFError, KeyboardInterrupt):
        print('\n[Session ended]')
        break
    if not user_input:
        continue
    if user_input.lower() in ('quit', 'exit', 'q', 'stop'):
        print('Agent: Goodbye!')
        break
    print(f'\nAgent: {agent.run(user_input)}\n')