# -*- coding: utf-8 -*-
"""ReinsuranceRAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQvLQvjT9pVZAg9vMumcjrfcoMVT_ZaN
"""

from google.colab import userdata
GROQ_API_KEY = userdata.get('GROQ_API_KEY')

from google.colab import drive
drive.mount('/content/drive')

!pip install rank-bm25

!pip install groq

!pip install langchain-community

!pip install langchain_huggingface

!pip install faiss-cpu

from rank_bm25 import BM25Okapi


class BM25Retriever:

    def __init__(self, chunks):

        self.chunks = chunks

        corpus = []

        for chunk in chunks:

            text = chunk["content"]

            tokens = text.lower().split()

            corpus.append(tokens)

        self.bm25 = BM25Okapi(corpus)

    def search(self, query, k=10):

        query_tokens = query.lower().split()

        scores = self.bm25.get_scores(query_tokens)

        ranked = sorted(
            zip(self.chunks, scores),
            key=lambda x: x[1],
            reverse=True
        )

        return ranked[:k]

import os
from groq import Groq

client = Groq(
    api_key=GROQ_API_KEY
)

def generate_answer(prompt):

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0,
        max_tokens=1000
    )

    return response.choices[0].message.content

from collections import defaultdict


class HybridRetriever:

    def __init__(
        self,
        faiss_vectorstore,
        bm25_retriever
    ):

        self.faiss = faiss_vectorstore
        self.bm25 = bm25_retriever

    def search(
        self,
        query,
        faiss_k=20,
        bm25_k=20,
        final_k=10
    ):

        combined = {}

        # =====================================
        # FAISS RESULTS
        # =====================================

        faiss_docs = self.faiss.similarity_search_with_score(
            query,
            k=faiss_k
        )

        for rank, (doc, score) in enumerate(faiss_docs):

            key = doc.page_content

            if key not in combined:

                combined[key] = {
                    "doc": doc,
                    "score": 0
                }

            combined[key]["score"] += (
                1.0 / (rank + 1)
            )

        # =====================================
        # BM25 RESULTS
        # =====================================

        bm25_docs = self.bm25.search(
            query,
            k=bm25_k
        )

        for rank, (chunk, score) in enumerate(bm25_docs):

            key = chunk["content"]

            if key not in combined:

                combined[key] = {
                    "doc": None,
                    "score": 0
                }

            combined[key]["score"] += (
                1.0 / (rank + 1)
            )

        # =====================================
        # SORT RESULTS
        # =====================================

        ranked_results = sorted(
            combined.values(),
            key=lambda x: x["score"],
            reverse=True
        )

        # =====================================
        # RETURN ONLY DOCUMENT OBJECTS
        # =====================================

        final_docs = []

        for item in ranked_results:

            if item["doc"] is not None:

                final_docs.append(
                    item["doc"]
                )

        return final_docs[:final_k]

# from llm_engine import generate_answer


class RagEngine:

    def __init__(self, retriever):

        self.retriever = retriever

    def ask(self, question):

        docs = self.retriever.search(
            query=question,
            final_k=10
        )

        context = ""

        for doc in docs:

            context += (
                f"\n\n{doc.page_content}"
            )

        prompt = f"""
            You are a Reinsurance Treaty Analysis Assistant.

            Instructions:

            1. Answer ONLY from the provided context.
            2. Do NOT use outside knowledge.
            3. If the answer is not found, say:
            "I could not find the answer in the provided documents."
            4. Mention the relevant Article or Section if available.
            5. Be concise and professional.

            CONTEXT:

            {context}

            QUESTION:

            {question}

            ANSWER:
            """

        answer = generate_answer(
            prompt
        )

        return answer

from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
import pickle
import sys
from types import ModuleType

# Custom unpickler to handle ModuleNotFoundError for BM25Retriever
# This class needs to be defined *before* the pickle.load call
# and needs to be aware of the BM25Retriever class which is defined in a previous cell (ow488h8obLjO).
class CustomUnpickler(pickle.Unpickler):
    def find_class(self, module, name):
        if module == 'bm25_engine' and name == 'BM25Retriever':
            # Return the BM25Retriever class from the current global scope
            return globals()['BM25Retriever']
        # Fall back to the default behavior for other classes
        return super().find_class(module, name)

with open("/content/drive/Shared with me/RI Project SSSIA/Student_7_RAG/bm25.pkl", "rb") as f:
    # Use the custom unpickler to load the BM25 object
    bm25 = CustomUnpickler(f).load()


# ====================================
# Embedding Model
# ====================================

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# ====================================
# Load FAISS
# ====================================

vectorstore = FAISS.load_local(
    "/content/drive/Shared with me/RI Project SSSIA/Student_7_RAG/vectorstore",
    embeddings,
    allow_dangerous_deserialization=True
)

# ====================================
# Hybrid Retriever
# ====================================

hybrid = HybridRetriever(
    vectorstore,
    bm25
)

# ====================================
# RAG Engine
# ====================================

rag = RagEngine(
    hybrid
)

print("\n")
print("=" * 80)
print("REINSURANCE TREATY ANALYZER")
print("=" * 80)

while True:

    question = input(
        "\nQuestion: "
    )

    if question.lower() == "exit":
        break

    try:

        answer = rag.ask(
            question
        )

        print("\n")

        print(answer)


    except Exception as e:

        print(
            f"\nError: {e}"
        )

!ls "/content/drive/RI Project SSSIA/"

!ls "/content/drive/MyDrive/ReinsuranceRAG/Student_7_RAG"