# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# @title 📊 CatPriceAI Underwriter Dashboard {display-mode: "form"}
import pandas as pd
import json
import base64
from IPython.display import HTML
from google.colab import output

# --- Error Handling & Image Saving Backend ---
def _report_js_error(message):
    print(f"JavaScript Error: {message}")

def save_dashboard_image(name, data_url):
    """Saves base64 image data from the frontend to the local file system."""
    try:
        # Strip the data:image/png;base64, header
        header, encoded = data_url.split(",", 1)
        data = base64.b64decode(encoded)
        with open(f"/content/{name}.png", "wb") as f:
            f.write(data)
    except Exception as e:
        print(f"Error saving {name}: {e}")

output.register_callback('report_js_error', _report_js_error)
output.register_callback('save_dashboard_image', save_dashboard_image)

# --- Data Loading ---
try:
    df_pricing = pd.read_csv('/content/pricing_output.csv')
    df_losses = pd.read_csv('/content/loss_summary.csv')
    df_feature = pd.read_csv('/content/feature_importance.csv')
    df_method = pd.read_csv('/content/method_comparison.csv')
    df_market = pd.read_csv('/content/market_rol.csv')
    df_exposure_summary = pd.read_csv('/content/exposure_summary.csv')
    df_port = pd.read_csv('/content/portfolio.csv')

    # Mapping for TIV by State
    df_state_tiv = df_port.groupby('state')['tiv_usd'].sum().reset_index().sort_values('tiv_usd', ascending=False)

    # Fix Expected Loss NaN: If expected_loss is missing or NaN, calc from ROL * Limit
    pricing_data = df_pricing.to_dict(orient='records')[0]
    if pd.isna(pricing_data.get('expected_loss')) or 'expected_loss' not in pricing_data:
        limit = pricing_data.get('layer_limit_m', 50) * 1e6
        pricing_data['expected_loss'] = pricing_data['technical_rol'] * limit

    data_payload = {
        "pricing": [pricing_data],
        "losses": df_losses.to_dict(orient='records'),
        "features": df_feature.to_dict(orient='records'),
        "method": df_method.to_dict(orient='records'),
        "market": df_market.to_dict(orient='records'),
        "exposure": df_state_tiv.to_dict(orient='records'),
        "summary": df_exposure_summary.to_dict(orient='records')
    }
except Exception as e:
    data_payload = {"error": str(e)}

html_template = """
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <script src='https://cdn.plot.ly/plotly-2.24.1.min.js'></script>
    <style>
        body { font-family: 'Segoe UI', sans-serif; background-color: #f4f6f8; padding: 20px; color: #333; }
        .dashboard-container { display: flex; flex-direction: column; gap: 20px; max-width: 1400px; margin: auto; }
        .kpi-row { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; }
        .card { background: white; padding: 15px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
        .kpi-value { font-size: 24px; font-weight: bold; color: #2c3e50; }
        .chart-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }
        .chart-container { background: white; padding: 15px; border-radius: 8px; min-height: 350px; display: flex; flex-direction: column; }
        .canvas-wrapper { position: relative; flex-grow: 1; min-height: 0; }
        h2 { font-size: 16px; border-left: 4px solid #3498db; padding-left: 10px; margin-top: 0; }
        .table-container { background: white; padding: 15px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); overflow-x: auto; max-height: 400px; }
        table { width: 100%; border-collapse: collapse; font-size: 12px; }
        th { position: sticky; top: 0; background: #f8f9fa; text-align: left; padding: 8px; border-bottom: 2px solid #dee2e6; }
        td { padding: 8px; border-bottom: 1px solid #eee; }
    </style>
</head>
<body>
    <div class='dashboard-container'>
        <div class='kpi-row'>
            <div class='card'><div>Technical ROL</div><div id='kpi-rol' class='kpi-value'>-</div></div>
            <div class='card'><div>Expected Loss</div><div id='kpi-el' class='kpi-value'>-</div></div>
            <div class='card'><div>Portfolio TIV</div><div id='kpi-tiv' class='kpi-value'>-</div></div>
        </div>
        <div class='chart-grid'>
            <div class='chart-container'><h2>1. TIV Exposure by State</h2><div id='c1' class='canvas-wrapper'></div></div>
            <div class='chart-container'><h2>2. Loss History Trend</h2><div id='c2' class='canvas-wrapper'></div></div>
            <div class='chart-container'><h2>3. Pricing Waterfall</h2><div id='c3' class='canvas-wrapper'></div></div>
            <div class='chart-container'><h2>4. Market Cycle Comparison</h2><div id='c4' class='canvas-wrapper'></div></div>
            <div class='chart-container'><h2>5. ML Risk Drivers</h2><div id='c5' class='canvas-wrapper'></div></div>
            <div class='chart-container'><h2>6. Pricing Method Comparison</h2><div id='c6' class='canvas-wrapper'></div></div>
        </div>
        <div class='table-container'>
            <h2>Historical Submission Data</h2>
            <table id='data-table'><thead><tr id='table-head'></tr></thead><tbody id='table-body'></tbody></table>
        </div>
    </div>
    <script>
        const data = DATA_PLACEHOLDER;

        async function autoSave(id, name) {
            // Use a higher resolution for saved files
            const imgData = await Plotly.toImage(id, {format: 'png', width: 1200, height: 900});
            google.colab.kernel.invokeFunction('save_dashboard_image', [name, imgData], {});
        }

        if(!data.error) {
            const p = data.pricing[0];
            document.getElementById('kpi-rol').innerText = (p.technical_rol * 100).toFixed(2) + '%';
            document.getElementById('kpi-el').innerText = '$' + (p.expected_loss/1e6).toFixed(2) + 'M';
            document.getElementById('kpi-tiv').innerText = '$' + (data.summary[0].Total_TIV / 1e6).toFixed(1) + 'M';

            // 1. TIV
            Plotly.newPlot('c1', [{
                x: data.exposure.map(d=>d.state),
                y: data.exposure.map(d=>d.tiv_usd),
                type: 'bar',
                marker: { color: data.exposure.map((v, i) => i === 0 ? '#e74c3c' : '#3498db') }
            }], {margin: {t:10, b:40}}).then(() => autoSave('c1', 'TIV_Exposure'));

            // 2. Loss History
            const lY = data.losses.map(d=>d.year), lA = data.losses.map(d=>d.annual_gross_loss);
            const maxL = Math.max(...lA);
            Plotly.newPlot('c2', [{x: lY, y: lA, type:'bar', marker:{color:'#95a5a6'}}], {margin: {t:10, b:40}, annotations:[{x:lY[lA.indexOf(maxL)], y:maxL, text:'Max Loss', showarrow:true}]}).then(() => autoSave('c2', 'Loss_History'));

            // 3. Waterfall
            Plotly.newPlot('c3', [{type:'waterfall', x:['Pure','Exp','Prof','Total'], y:[p.blended_pure_rol, p.expense_load, p.profit_load, p.technical_rol], measure:['relative','relative','relative','total']}], {margin: {t:10, b:40}}).then(() => autoSave('c3', 'Pricing_Waterfall'));

            // 4. Market Cycle
            const mY = [...new Set(data.market.map(d => d.year))];
            const mR = mY.map(y => { const sub = data.market.filter(d => d.year === y); return sub.reduce((a, b) => a + b.market_rol, 0) / sub.length; });
            Plotly.newPlot('c4', [{x:mY, y:mR, mode:'lines+markers'}], {margin: {t:10, b:40}}).then(() => autoSave('c4', 'Market_Cycle'));

            // 5. Drivers
            Plotly.newPlot('c5', [{y: data.features.map(d => d.feature_name), x: data.features.map(d => d.importance_score), type: 'bar', orientation: 'h', marker: { color: '#8e44ad' }}], { margin: {t:10, l:150} }).then(() => autoSave('c5', 'ML_Drivers'));

            // 6. Methods
            Plotly.newPlot('c6', [{x:data.method.map(d=>d.method), y:data.method.map(d=>d.pure_rol), type:'bar'}], {margin: {t:10, b:40}}).then(() => autoSave('c6', 'Method_Comparison'));

            // Table Build
            const keys = Object.keys(data.losses[0]);
            const head = document.getElementById('table-head');
            const body = document.getElementById('table-body');
            keys.forEach(k => { const th = document.createElement('th'); th.innerText = k.toUpperCase(); head.appendChild(th); });
            data.losses.forEach(row => {
                const tr = document.createElement('tr');
                keys.forEach(k => { const td = document.createElement('td'); td.innerText = typeof row[k] === 'number' ? row[k].toLocaleString() : row[k]; tr.appendChild(td); });
                body.appendChild(tr);
            });
        }
    </script>
</body>
</html>
"""
HTML(html_template.replace("DATA_PLACEHOLDER", json.dumps(data_payload)))