-- CatPriceAI Schema Reference
-- SQLite database: data/catprice.db
-- Generated by: 01_generate_data.py

-- ─────────────────────────────────────────────────────────────────
-- TABLE 1: portfolio — Cedant exposure data (one row per location)
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS portfolio (
    location_id         TEXT PRIMARY KEY,     -- e.g., LOC0001
    state               TEXT NOT NULL,        -- TX, LA, MS, AL, FL
    latitude            REAL,
    longitude           REAL,
    tiv_usd             REAL NOT NULL,        -- Total Insured Value in USD
    construction_type   TEXT,                 -- Wood Frame, Masonry, Steel Frame, Manufactured
    occupancy_type      TEXT,                 -- Residential, Commercial, Industrial, Mixed Use
    year_built          INTEGER,
    wind_vuln_index     REAL,                 -- 1 (low) to 5 (high)
    dist_to_coast_km    REAL,
    flood_zone          TEXT                  -- FEMA zone: A, AE, X, AH
);

-- ─────────────────────────────────────────────────────────────────
-- TABLE 2: loss_events — Historical catastrophe losses
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS loss_events (
    event_id            TEXT NOT NULL,        -- e.g., EVT0001
    year                INTEGER NOT NULL,
    event_name          TEXT NOT NULL,        -- e.g., Katrina, Harvey
    peril               TEXT NOT NULL,        -- Hurricane, Flood
    landfall_state      TEXT,
    affected_state      TEXT NOT NULL,
    industry_loss_bn    REAL,                 -- Industry-wide loss in billions
    gross_loss_usd      REAL NOT NULL,        -- Cedant gross loss USD
    cedant_name         TEXT
);

-- ─────────────────────────────────────────────────────────────────
-- TABLE 3: treaty_terms — The Cat XL treaty structure
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS treaty_terms (
    treaty_id               TEXT PRIMARY KEY,
    cedant_name             TEXT,
    treaty_type             TEXT,             -- Cat XL
    layer_attachment_usd    REAL,             -- $50M — reinsurer pays above this
    layer_limit_usd         REAL,             -- $50M — max reinsurer pays
    layer_exhaustion_usd    REAL,             -- $100M — attachment + limit
    perils_covered          TEXT,             -- semicolon-separated
    territories             TEXT,             -- semicolon-separated state codes
    inception_date          TEXT,
    expiry_date             TEXT,
    reinstatements          INTEGER,          -- number of reinstatements permitted
    aggregate_retention     REAL,
    cession_pct             REAL,
    provisional_rate_pct    REAL             -- filled after pricing run
);

-- ─────────────────────────────────────────────────────────────────
-- TABLE 4: market_rol — Historical market Rate-on-Line data
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS market_rol (
    year        INTEGER NOT NULL,
    region      TEXT NOT NULL,
    peril       TEXT NOT NULL,
    market_rol  REAL NOT NULL    -- e.g., 0.18 = 18% of layer limit
);

-- ─────────────────────────────────────────────────────────────────
-- USEFUL QUERIES (run in DB Browser for SQLite or Python)
-- ─────────────────────────────────────────────────────────────────

-- Q1: TIV breakdown by state
-- SELECT state, COUNT(*) AS locations, SUM(tiv_usd)/1e6 AS tiv_m
-- FROM portfolio GROUP BY state ORDER BY tiv_m DESC;

-- Q2: Catastrophe losses by year
-- SELECT year, SUM(gross_loss_usd)/1e6 AS total_loss_m
-- FROM loss_events GROUP BY year ORDER BY total_loss_m DESC;

-- Q3: Loss frequency by peril
-- SELECT peril, COUNT(DISTINCT event_id) AS events, SUM(gross_loss_usd)/1e6 AS total_loss_m
-- FROM loss_events GROUP BY peril;

-- Q4: Top 5 loss events ever
-- SELECT event_name, year, peril, SUM(gross_loss_usd)/1e6 AS loss_m
-- FROM loss_events GROUP BY event_id ORDER BY loss_m DESC LIMIT 5;
